Fix NoClassDefFoundError for optional dependency (#23)
* Fix NoClassDefFoundError for optional dependency

* Remove unused imports

* Add negative Junit tests

* Remove unused imports